/**
 * PDF Export utility using jsPDF and jspdf-autotable.
 * Generates a professional storage configuration report.
 */

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Drive } from '@/types/drive'
import type { CalculationResults } from '@/types/results'
import type { Topology, ZfsOptions } from '@/types/topology'
import { formatBytes as formatBytesUtil, type UnitSystem } from './units'

interface ExportConfig {
  drive: Drive
  driveCount: number
  topology: Topology
  zfsOptions?: ZfsOptions
  results: CalculationResults
  projectName?: string
  unitSystem?: UnitSystem
}

/**
 * Format number with commas.
 */
function formatNumber(value: number): string {
  return new Intl.NumberFormat('en-US').format(Math.round(value))
}

/**
 * Generate and download a PDF report.
 */
export function exportToPdf(config: ExportConfig): void {
  const {
    drive,
    driveCount,
    topology,
    zfsOptions,
    results,
    projectName = 'Storage Configuration',
    unitSystem = 'binary',
  } = config

  // Create a local formatBytes function using the specified unit system
  const formatBytes = (bytes: number) => formatBytesUtil(bytes, unitSystem)
  const { volumetry, performance, sustainability, resilience } = results

  // Create PDF document
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // Title
  doc.setFontSize(20)
  doc.setTextColor(30, 64, 175) // Blue
  doc.text(projectName, pageWidth / 2, y, { align: 'center' })
  y += 10

  // Subtitle
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated by Raidy - ${new Date().toLocaleDateString()}`, pageWidth / 2, y, {
    align: 'center',
  })
  y += 15

  // Hardware Configuration Section
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Hardware Configuration', 14, y)
  y += 8

  autoTable(doc, {
    startY: y,
    head: [['Parameter', 'Value']],
    body: [
      ['Drive Model', drive.model],
      ['Drive Type', drive.type + (drive.formFactor ? ` (${drive.formFactor})` : '')],
      ['Drive Capacity', formatBytes(drive.capacity_raw)],
      ['Drive Count', driveCount.toString()],
      ['Topology', `${topology.type.toUpperCase()} - ${topology.level}`],
      ['Raw Capacity', formatBytes(volumetry.rawCapacity)],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175] },
  })

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  // Capacity Analysis Section
  doc.setFontSize(14)
  doc.text('Capacity Analysis', 14, y)
  y += 8

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value', 'Percentage']],
    body: [
      ['Raw Capacity', formatBytes(volumetry.rawCapacity), '100%'],
      [
        'Parity Overhead',
        formatBytes(volumetry.parityOverhead),
        `${((volumetry.parityOverhead / volumetry.rawCapacity) * 100).toFixed(1)}%`,
      ],
      [
        'Hot Spare Overhead',
        formatBytes(volumetry.hotSpareOverhead),
        `${((volumetry.hotSpareOverhead / volumetry.rawCapacity) * 100).toFixed(1)}%`,
      ],
      [
        'Filesystem Overhead',
        formatBytes(volumetry.filesystemOverhead),
        `${((volumetry.filesystemOverhead / volumetry.rawCapacity) * 100).toFixed(1)}%`,
      ],
      [
        'ZFS Slop',
        formatBytes(volumetry.slopOverhead),
        `${((volumetry.slopOverhead / volumetry.rawCapacity) * 100).toFixed(1)}%`,
      ],
      [
        'Usable Capacity',
        formatBytes(volumetry.usableCapacity),
        `${volumetry.efficiency.toFixed(1)}%`,
      ],
      ['Effective Capacity', formatBytes(volumetry.effectiveCapacity), '-'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175] },
  })

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  // Performance Section
  doc.setFontSize(14)
  doc.text('Performance Metrics', 14, y)
  y += 8

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Max Read Throughput', `${formatNumber(performance.maxReadThroughputMBs)} MB/s`],
      ['Max Write Throughput', `${formatNumber(performance.maxWriteThroughputMBs)} MB/s`],
      ['Max Read IOPS', formatNumber(performance.maxReadIOPS)],
      ['Max Write IOPS', formatNumber(performance.maxWriteIOPS)],
      ['Bottleneck', performance.bottleneckDescription],
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 64, 175] },
  })

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  // Check if we need a new page
  if (y > 240) {
    doc.addPage()
    y = 20
  }

  // Sustainability Section
  doc.setFontSize(14)
  doc.text('Power & Sustainability', 14, y)
  y += 8

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Total Power', `${formatNumber(sustainability.powerBreakdown.total)} W`],
      ['Drive Power', `${formatNumber(sustainability.powerBreakdown.drives)} W`],
      ['Server Power', `${formatNumber(sustainability.powerBreakdown.servers)} W`],
      ['Cooling (PUE)', `${formatNumber(sustainability.powerBreakdown.cooling)} W`],
      ['Annual Energy', `${formatNumber(sustainability.annualEnergyKwh)} kWh`],
      ['Annual CO₂', `${formatNumber(sustainability.annualCO2Kg)} kg`],
    ],
    theme: 'striped',
    headStyles: { fillColor: [34, 197, 94] }, // Green
  })

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  // Resilience Section (if available)
  if (resilience) {
    if (y > 200) {
      doc.addPage()
      y = 20
    }

    doc.setFontSize(14)
    doc.text('Data Resilience (Monte Carlo Simulation)', 14, y)
    y += 8

    autoTable(doc, {
      startY: y,
      head: [['Metric', 'Value']],
      body: [
        ['Survival Rate', resilience.survivalPercent],
        ['Nines', resilience.nines.toString()],
        ['Risk Level', resilience.riskLevel.toUpperCase()],
        ['Avg Rebuild Time', `${resilience.avgRebuildTimeHours.toFixed(1)} hours`],
        ['URE Probability', `${(resilience.ureProbability * 100).toFixed(4)}%`],
        ['Dual Failure Probability', `${(resilience.dualFailureProbability * 100).toFixed(4)}%`],
      ],
      theme: 'striped',
      headStyles: {
        fillColor:
          resilience.riskLevel === 'low'
            ? [34, 197, 94]
            : resilience.riskLevel === 'medium'
              ? [234, 179, 8]
              : resilience.riskLevel === 'high'
                ? [249, 115, 22]
                : [239, 68, 68],
      },
    })

    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

    // Recommendations
    if (resilience.recommendations.length > 0) {
      doc.setFontSize(12)
      doc.text('Recommendations:', 14, y)
      y += 6
      doc.setFontSize(10)
      for (const rec of resilience.recommendations) {
        doc.text(`• ${rec}`, 18, y)
        y += 5
      }
    }
  }

  // ZFS Commands (if applicable)
  if (topology.type === 'zfs' && zfsOptions) {
    if (y > 220) {
      doc.addPage()
      y = 20
    }

    doc.setFontSize(14)
    doc.text('ZFS Configuration Commands', 14, y)
    y += 8

    doc.setFontSize(9)
    doc.setTextColor(50, 50, 50)

    const commands = [
      `# Create ZFS pool with ${topology.level}`,
      `zpool create -o ashift=${zfsOptions.ashift} tank ${topology.level} /dev/sd[a-z]`,
      '',
      `# Set recordsize`,
      `zfs set recordsize=${zfsOptions.recordsize / 1024}K tank`,
    ]

    if (zfsOptions.compression) {
      commands.push(
        '',
        `# Enable compression`,
        `zfs set compression=${zfsOptions.compressionType} tank`,
      )
    }

    if (zfsOptions.dedup) {
      commands.push('', `# Enable deduplication (RAM-intensive!)`, `zfs set dedup=on tank`)
    }

    for (const cmd of commands) {
      doc.text(cmd, 14, y)
      y += 5
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Page ${i} of ${pageCount} | Generated by Raidy Storage Calculator`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' },
    )
  }

  // Download
  doc.save(`${projectName.replace(/\s+/g, '_')}_Report.pdf`)
}
